### ISSUE TITLE
Form to fill json values

### ISSUE THREAD

**Issue by fasteddys** [antifree/json-to-variables#1]
Hi this is a very nice idea, it would be nice to have a form or data grid to enter values into the table like a resz designer for languages.

For e.g. we have measurements and formula. and there are json variable for it, but every time we are manually changing it by country (metric/british etc).  Foot Pound vs Meter KG etc

So, if this had some form to enter the values, then the user can select a drop down in their asp core app to pull the values it would be nice

**Comment by antifree** [comment]
Hi @fasteddys,

I think this request is out of the scope of this project. 
It is a small project with a script that enables to configure environment variables in the pipeline through JSON files.
