### ISSUE TITLE
Add option for no prefix

### ISSUE THREAD

**Issue by djthornton1212** [antifree/json-to-variables#2]
Hello and thank you for creating this application. I'm vary surprised that this is used wider.

I can see it's been a while since you've made any changes to this Actions, so I'm not sure if you're still working with it. If so, I'd like to suggest a way we can have an empty prefix. I pull configs from my config server and read them into the environment variables. The configs are named exactly as they should be, so the prefix kind of breaks that.

I've tried sending an empty string, but that's just as not adding the `prefix:` keyword thus the default still kicks in.

Is there a way to do this with how it's currently designed?

**Comment by antifree** [comment]
Hi! 
Sorry for the late response.
Thanks for the proposal!
I can update the logic in a way if prefix is empty string, do not set default value for it.

**Comment by hadrienj** [comment]
Thanks for the project @antifree!

I agree that would be a great feature to have no prefix if it is not set!

**Comment by mncorreia** [comment]
@hadrienj I added this solution at my PR https://github.com/antifree/json-to-variables/pull/5
