### ISSUE TITLE
Replace old Node.j with Node.js 20

### ISSUE THREAD

**Issue by Gershon-A** [antifree/json-to-variables#9]
GitHub actions is planning to [deprecate Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). The file existence action is still using Node 16. We are getting this warning that the file exists action should be updated to Node 20

**Comment by antifree** [comment]
Thanks I'll take a look

**Comment by Jmainguy** [comment]
https://github.com/antifree/json-to-variables/pull/11 should resolve this

**Comment by Gershon-A** [comment]
Thanks

**Comment by antifree** [comment]
Thanks for your contribution
